# site settings
title: Julie Love Sherman's Personal Webpage
subtitle: A learning experience
email: jls@julielovesherman.com
description: Developing my personal website
baseurl: / # the subpath of your site, e.g. /blog
url: https://julielovesherman.com # the base hostname & protocol for your site
author: Julie Love Sherman

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2 # 6

# social settings
github_url: https://github.com/julielsherman
youtube_url: https://www.youtube.com/channel/UCxOvTfDgnDjXsbqm7_OpLGw

# build settings
markdown: kramdown

sass:
  style: compressed
